import type { Tx } from '@pospay/db';
import { sql } from 'drizzle-orm';

export interface RegisterCompanyInput {
  readonly id: string;
  readonly nameEn: string;
  readonly nameAr: string | null;
  readonly ownerUserId: string;
  readonly planId: string;
}

export interface RegisteredCompany extends RegisterCompanyInput {
  /** ISO 8601 as Postgres writes it — the same text every read of this company returns. */
  readonly createdAt: string;
}

/**
 * Inserts one company row inside the caller's transaction and does nothing else — the one write tenancy exports
 * (module-map.md §3, ADR-0003 §5.3). Its only caller is identity's onboard-company, which adds the owner
 * membership, audit row and event in the same transaction.
 *
 * @param tx    the caller's transaction, opened by withNewTenant for this company id
 * @param input the company, its id generated by withNewTenant
 * @returns the inserted row
 */
export async function registerCompany(
  tx: Tx,
  input: RegisterCompanyInput,
): Promise<RegisteredCompany> {
  const [row] = await tx.execute<{ created_at: string }>(sql`
    INSERT INTO companies (id, name_en, name_ar, owner_user_id, plan_id)
    VALUES (${input.id}, ${input.nameEn}, ${input.nameAr}, ${input.ownerUserId}, ${input.planId})
    RETURNING to_json(created_at) #>> '{}' AS created_at`);
  if (row === undefined) throw new Error('companies insert returned no row');
  return { ...input, createdAt: row.created_at };
}
